### ISSUE TITLE
Adfly link redirects to virus sites.

### ISSUE THREAD

**Issue by DanielElam** [GreyDynamics/Frostbite3_Editor#1]
The adfly link to download the zip on the github.io page redirects to "hondaschik.40chrome.ru". It should really link straight to https://github.com/GreyDynamics/Frostbite3_Editor/archive/develop.zip

**Comment by GreyDynamics** [comment]
Thank you very much Dan for reporting this issue.
The adf.ly link is correct. Sadly Firefox/Nightly (and maybe your browser)
have a problem by directly linking files. Opera, Chrome, Dolphin and Yandex
browser have not this problem. The next code push will include alternative
download methods.

(note to others: the download is also accessible on the github repository
page under releases.)

Regards ~Grey
