### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by x1game1xGER** [GreyDynamics/Frostbite3_Editor#1]
I can offer Linux / Windows dedicated servers! 16/32GB RAM 8-Core I7 1Gbit

**Comment by x1game1xGER** [comment]
Join Ts3: soos.li I want a mod for bf3, open world :D

**Comment by x1game1xGER** [comment]
http://flipwire.network/do.php?v=9kvGrOzKz2vRm8er.zip in case of deleting

**Comment by GreyDynamics** [comment]
Hey x1game1xGER,

>its nice that you want to contribute!
>You should get in contact with youtube.com/user/greeen49
>he can tell you where servers needed for ZLOEmu.

Thanks
