### ISSUE TITLE
How do I edit a map? And is it possible to modify code?

### ISSUE THREAD

**Issue by x1game1xGER** [GreyDynamics/Frostbite3_Editor#2]

**Comment by GreyDynamics** [comment]
Code modification on games is not possible without the Source. This Editor will allow soon to modify any game logic or static data defined in EBX files. Changing the Structure of a Map will be possible too. Right now the project is in "early" development stage and a lot of features are missing, bugged or not accessible to public.You can follow the current progress at http://greydynamics.github.io/Frostbite3_Editor/
If you are interested in Battlefield 4,you also have to wait for ZLOEmu opens to public.

**Comment by x1game1xGER** [comment]
Sorry, but is there a way to contact you personally?

**Comment by GreyDynamics** [comment]
Sure. You can find my Twitter and Youtube directly on the github page of
the editor. If you want to, also via mail greydynamics@gmail.com
Please keep in mind, there is no support given for the editor yet.
